---
- name: Golden Download
  become: yes
  become_user: "{{ mobyle_user }}"
# because of bug https://github.com/ansible/ansible-modules-core/issues/3661
# on ansible version 2.0.2.0 we can not use get_url : workaround use command
#  get_url: url=ftp://ftp.pasteur.fr/pub/gensoft/projects/golden/golden-1.1a.tar.gz dest=~/src/
  command: curl ftp://ftp.pasteur.fr/pub/gensoft/projects/golden/golden-1.1a.tar.gz -o ~/src/golden-1.1a.tar.gz

- name: Golden Unarchive
  become: yes
  become_user: "{{ mobyle_user }}"
  unarchive: src=~/src/golden-1.1a.tar.gz dest=~/src creates=~/src/golden-1.1a copy=no

- name: Golden configure
  become: yes
  become_user: "{{ mobyle_user }}"
  command: ./configure --prefix={{mobyle_home.stdout}} chdir=~/src/golden-1.1a creates=Makefile

- name: Golden make
  become: yes
  become_user: "{{ mobyle_user }}"
  command: make chdir=~/src/golden-1.1a

- name: Golden Install
  become: yes
  become_user: "{{ mobyle_user }}"
  command: make install chdir=~/src/golden-1.1a

