---
- name: register mobyle_home
  become: yes
  become_user: "{{ mobyle_user }}"
  shell: grep '^mobyle' /etc/passwd | cut -d ':' -f6
  changed_when: false
  register: mobyle_home

- name: libxml2 Download
  become: yes
  become_user: "{{ mobyle_user }}"
# because of bug https://github.com/ansible/ansible-modules-core/issues/3661
# on ansible version 2.0.2.0 we can not use get_url : workaround use command
# get_url: url=ftp://xmlsoft.org/libxml2/libxml2-2.9.3.tar.gz dest=~/src/
  command: curl ftp://xmlsoft.org/libxml2/libxml2-2.9.3.tar.gz -o ~/src/libxml2-2.9.3.tar.gz

- name: libxml2 Extract
  become: yes
  become_user: "{{ mobyle_user }}"
  unarchive: src=~/src/libxml2-2.9.3.tar.gz dest=~/src creates=~/src/libxml2-2.9.3 copy=no

- name: libxml2 configure
  become: yes
  become_user: "{{ mobyle_user }}"
  command: ./configure --prefix={{mobyle_home.stdout}} --without-python chdir=~/src/libxml2-2.9.3 creates=Makefile

- name: libxml2 make
  become: yes
  become_user: "{{ mobyle_user }}"
  command: make chdir=~/src/libxml2-2.9.3

- name: libxml2 Install
  become: yes
  become_user: "{{ mobyle_user }}"
  command: make install chdir=~/src/libxml2-2.9.3
