---
- name: register mobyle_home
  become: yes
  become_user: "{{ mobyle_user }}"
  shell: grep '^mobyle' /etc/passwd | cut -d ':' -f6
  changed_when: false
  register: mobyle_home

- name: libxslt Download
  become: yes
  become_user: "{{ mobyle_user }}"
# because of bug https://github.com/ansible/ansible-modules-core/issues/3661
# on ansible version 2.0.2.0 we can not use get_url : workaround use command
#  get_url:  url=ftp://xmlsoft.org/libxml2/libxslt-1.1.28.tar.gz dest=~/src/
  command: curl ftp://xmlsoft.org/libxml2/libxslt-1.1.28.tar.gz -o ~/src/libxslt-1.1.28.tar.gz

- name: libxslt Extract
  become: yes
  become_user: "{{ mobyle_user }}"
  unarchive: src=~/src/libxslt-1.1.28.tar.gz dest=~/src creates=~/src/libxslt-1.1.28 copy=no

- name: libxslt configure
  become: yes
  become_user: "{{ mobyle_user }}"
  command: ./configure --prefix={{mobyle_home.stdout}} --without-python --with-libxml-prefix={{mobyle_home.stdout}} chdir=~/src/libxslt-1.1.28 creates=Makefile

- name: libxslt make
  become: yes
  become_user: "{{ mobyle_user }}"
  command: make chdir=~/src/libxslt-1.1.28

- name: libxslt Install
  become: yes
  become_user: "{{ mobyle_user }}"
  command: make install chdir=~/src/libxslt-1.1.28
