---
- name: register mobyle_home
  become: yes
  become_user: mobyle
  shell: grep '^mobyle' /etc/passwd | cut -d ':' -f6
  changed_when: false
  register: mobyle_home

- name: Create src directory
  become: yes
  become_user: mobyle
  file: path=~/src/ state=directory

- name: Python Download
  become: yes
  become_user: mobyle
  get_url: url=https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz dest=~/src/
  tags: install_python

- name: Python Unarchive
  become: yes
  become_user: mobyle
  unarchive: src=~/src/Python-2.7.11.tgz dest=~/src creates=~/src/Python-2.7.11 copy=no
  tags: install_python

- name: Python configure
  become: yes
  become_user: mobyle
  command: ./configure --prefix={{mobyle_home.stdout}} chdir=~/src/Python-2.7.11 creates=Makefile

- name: Python make
  become: yes
  become_user: mobyle
  command: make chdir=~/src/Python-2.7.11

- name: Python Install
  become: yes
  become_user: mobyle
  command: make install chdir=~/src/Python-2.7.11

- name: setuptools Download
  become: yes
  become_user: mobyle
  get_url:  url=https://pypi.python.org/packages/source/s/setuptools/setuptools-20.7.0.tar.gz#md5=5d12b39bf3e75e80fdce54e44b255615 dest=~/src/

- name: setuptools Extract
  become: yes
  become_user: mobyle
  unarchive: src=~/src/setuptools-20.7.0.tar.gz dest=~/src creates=~/src/setuptools-20.7.0 copy=no

- name: setuptools Build
  become: yes
  become_user: mobyle
  shell: ~/bin/python setup.py build  chdir=~/src/setuptools-20.7.0

- name: setuptools Install
  become: yes
  become_user: mobyle
  command: ~/bin/python setup.py install chdir=~/src/setuptools-20.7.0

- name: BioPython Install
  become: yes
  become_user: mobyle
  command: ~/bin/easy_install biopython

- name: libxml2 Download
  become: yes
  become_user: mobyle
  get_url:  url= dest=~/src/

- name: libxml2 Extract
  become: yes
  become_user: mobyle
  unarchive: src=~/src/ dest=~/src creates=~/src/ copy=no

- name: libxml2 configure
  become: yes
  become_user: mobyle
  command: ./configure --prefix={{mobyle_home.stdout}} chdir=~/src/ creates=Makefile

- name: libxml2 make
  become: yes
  become_user: mobyle
  command: make chdir=~/src/

- name: libxml2 Install
  become: yes
  become_user: mobyle
  command: make install chdir=~/src/
