---
- name: Creation of "mobyle" user
  user: name=mobyle comment="Mobyke application user" home={{ mobyle_home }} shell=/bin/bash state=present

- name: Create src directory
  become: yes
  become_user: "{{ mobyle_user }}"
  file: path=~/src/ state=directory
