---

- name: Creation of "mobyle" user
  user:
    name={{ mobyle_user }}
    group=apache
    comment="Mobyle application user"
    home={{ mobyle_home }}
    shell=/bin/bash
    state=present

- name: Create src directory
  become: yes
  become_user: "{{ mobyle_user }}"
  file:
    path={{ mobyle_home }}/src/
    state=directory
    owner={{ mobyle_user }}
    group=apache
    mode=775
