---
- name: Creation of "mobyle" user
  user: name="{{ mobyle_user }}" comment="Mobyle application user" shell=/bin/bash state=present

- name: Creation of "mobyle" group
  group: name="{{ mobyle_user }}" comment="Mobyle application group" shell=/bin/bash state=present

- name: register mobyle_home
  become: yes
  become_user: mobyle
  shell: grep '^mobyle' /etc/passwd | cut -d ':' -f6
  changed_when: false
  register: mobyle_home

- name: Create src directory
  become: yes
  become_user: mobyle
  file: path=~/src/ state=directory
