#! /bin/sh

PATH=/usr/bin:/bin
export PATH

target_files='session_log'

cd $HOME/web/mobyle/log/mobyle || exit 1

rev=`cat .week`

## Save old files
for file in $target_files
do
	mv $file $file.$rev
	touch $file && chmod 644 $file
done

## Compress old files
for file in $target_files
do
	chmod 660 $file.$rev && gzip $file.$rev
done

date +%Y%m%d >.week

exit 0
