---
- name: register mobyle_home
  become: yes
  become_user: "{{ mobyle_user }}"
  shell: grep '^mobyle' /etc/passwd | cut -d ':' -f6
  changed_when: false
  register: mobyle_home

# the 3.5.0 version doesn not honored -I -L option so lxml is always linked to system libraries
# the 2.3.1 is used by Mobyle in production from long time at pasteur so use this version

- name: libxml Download
  become: yes
  become_user: "{{ mobyle_user }}"
  get_url:  url=http://lxml.de/files/lxml-2.3.1.tgz dest=~/src/

- name: libxml Extract
  become: yes
  become_user: "{{ mobyle_user }}"
  unarchive: src=~/src/lxml-2.3.1.tgz dest=~/src creates=~/src/lxml-2.3.1 copy=no

- name: libxml build
  become: yes
  become_user: "{{ mobyle_user }}"
  command: ~/bin/python setup.py build_ext -i -I {{mobyle_home.stdout}}/include/libxml2/ -L{{mobyle_home.stdout}}/lib/ --rpath={{mobyle_home.stdout}}/lib  --with-xslt-config={{mobyle_home.stdout}}/bin/xslt-config chdir=~/src/lxml-2.3.1

- name: libxml Install
  become: yes
  become_user: "{{ mobyle_user }}"
  command: ~/bin/python setup.py install chdir=~/src/lxml-2.3.1